version: '3'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - sitesvc
      - apisvc
      - staticsvc
      - ssrsvc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 8081:8081

  apisvc:
    image: olegsmetanin/filewatch:0.0.3-alpine3.7
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/apisvc.dev.sh
    expose:
      - "8080"
      - "8081"
    environment:
      - GO_MODE=development
      - TCP_PORTS=8081
      - VIRTUAL_HOST=*/rest,*/rest/*
      - VIRTUAL_HOST_WEIGHT=1
      - REST_PATH=/rest
      - REST_URL=${REST_URL}
      - SITE_URL=${SITE_URL}
      - AUTH_FB_APPID=${AUTH_FB_APPID}
      - AUTH_FB_APPSECRET=${AUTH_FB_APPSECRET}

  sitesvc:
    image: olegsmetanin/filewatch:0.0.3-alpine3.7
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/sitesvc.dev.sh
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=*
      - GO_MODE=development
      - REST_URL=${REST_URL}
      - RECAPTCHA_KEY=${RECAPTCHA_KEY}

  usersvc:
    image: olegsmetanin/filewatch:0.0.3-alpine3.7
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/usersvc.dev.sh
    expose:
      - "8081"

  ssrsvc:
    build: dev/webbuilder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/ssrsvc.dev.sh
    expose:
      - "8080"
    environment:
      - STATIC_CONTEXT=${STATIC_CONTEXT}

  staticsvc:
    image: nginx:1.13.10-alpine
    volumes:
      - ./web/nginx.tmpl:/etc/nginx/nginx.tmpl
      - ./web:/usr/share/nginx/html
    command: sh -c "envsubst < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=*/static,*/static/*
      - VIRTUAL_HOST_WEIGHT=1
      - STATIC_CONTEXT=${STATIC_CONTEXT}

  srvbuilder:
    build: dev/srvbuilder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/srvbuilder.dev.sh
    environment:
      - REST_URL=${REST_URL}

  webbuilder:
    build: dev/webbuilder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/webbuilder.dev.sh
    environment:
      - REST_URL=${REST_URL}
      - RECAPTCHA_KEY=${RECAPTCHA_KEY}
      - STATIC_CONTEXT=${STATIC_CONTEXT}

  mobilebuilder:
    build: dev/mobilebuilder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/mobilebuilder.dev.sh
    environment:
      - REST_URL=${REST_URL}
    ports:
      - 19000:19000
      - 19001:19001

  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    # volumes:
    #    - /data/postgres:/data/postgres
    # ports:
    #   - "5432:5432"
    # networks:
    #   - postgres
    restart: unless-stopped

  pgadmin:
    links:
      - pg
    image: fenglc/pgadmin4
    # volumes:
    #    - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    # networks:
    #   - postgres
    restart: unless-stopped
    # user: pgadmin4@pgadmin.org
    # password: admin

  # Other services

