version: '3'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - site
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80

  site:
    image: golang:1.9.2-stretch
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./site.dev.sh
    expose:
      - "8080"
    environment:
      - URL_BASE_PATH=/api
    depends_on:
      - "api"

  api:
    image: golang:1.9.2-stretch
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./api.dev.sh
    expose:
      - "8081"
      - "8082"
    ports:
      - 8081:8081
      - 8082:8082
    environment:
      - URL_BASE_PATH=/api
    depends_on:
      - "protowatcher"

  #front:
    #image: node:9.2.0-alpine
    #working_dir: /home/node/front
    #environment:
      #- NODE_ENV=development
    #volumes:
      #- ./front:/home/node/front
    #expose:
      #- "8080"
    #command: sh ./dev.sh

  protowatcher:
    build: protowatcher
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./protowatch.dev.sh

# Other services
