version: '3'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - sitesvc
      - apisvc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 8081:8081

  apisvc:
    image: olegsmetanin/alpine-inotify:0.0.1-alpine3.4
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/apisvc.dev.sh
    expose:
      - "8080"
      - "8081"
    environment:
      - GO_MODE=development
      - TCP_PORTS=8081
      - VIRTUAL_HOST=*/rest,*/rest/*
      - VIRTUAL_HOST_WEIGHT=1
      - REST_PATH=/rest
      - REST_URL=${REST_URL}
      - SITE_URL=${SITE_URL}
      - AUTH_FB_APPID=${AUTH_FB_APPID}
      - AUTH_FB_APPSECRET=${AUTH_FB_APPSECRET}
    depends_on:
      - "srvbuilder"

  sitesvc:
    image: olegsmetanin/alpine-inotify:0.0.1-alpine3.4
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/sitesvc.dev.sh
    expose:
      - "8080"
    environment:
      - GO_MODE=development
      - REST_URL=${REST_URL}
      - VIRTUAL_HOST=*
      - RECAPTCHA_KEY=${RECAPTCHA_KEY}
    depends_on:
      - "srvbuilder"
      - "webbuilder"

  usersvc:
    image: olegsmetanin/alpine-inotify:0.0.1-alpine3.4
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/usersvc.dev.sh
    expose:
      - "8081"
    depends_on:
      - "srvbuilder"
      - "pg"

  srvbuilder:
    build: dev/srvbuilder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/srvbuilder.dev.sh
    depends_on:
      - "webbuilder"

  webbuilder:
    build: dev/webbuilder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./dev/webbuilder.dev.sh
    environment:
      - REST_URL=${REST_URL}

  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    # volumes:
    #    - /data/postgres:/data/postgres
    # ports:
    #   - "5432:5432"
    # networks:
    #   - postgres
    restart: unless-stopped

  pgadmin:
    links:
      - pg
    image: fenglc/pgadmin4
    # volumes:
    #    - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    # networks:
    #   - postgres
    restart: unless-stopped
    # user: pgadmin4@pgadmin.org
    # password: admin

  # Other services

