version: '3'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - site
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 8081:8081
      - 8082:8082

  api:
    image: olegsmetanin/alpine-inotify:3.4
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./api.dev.sh
    expose:
      - "8081"
      - "8082"
    environment:
      - TCP_PORTS=8081,8082
    depends_on:
      - "builder"

  site:
    image: olegsmetanin/alpine-inotify:3.4
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./site.dev.sh
    expose:
      - "8080"
    environment:
      - URL_BASE_PATH=/site
    depends_on:
      - "builder"

  builder:
    build: builder
    volumes:
      - .:/go/src/github.com/olegsmetanin/startup_boilerplate
    working_dir: /go/src/github.com/olegsmetanin/startup_boilerplate
    command: sh ./builder.dev.sh

# Other services
